name: build and test the application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Run unit tests 
      run: npm run test:unit
    - name: mitko_dimitrov
      run: echo @mitko_dimitrov
      
  deploy:
    needs: build-test    
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the app
        uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          
  Test-Ui:
   
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run UI tests 
      run: npm run test:ui
  
